DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, NUMERO_MATRICULA NUMERIC NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);


-- para test --
INSERT INTO  ODONTOLOGOS(NUMERO_MATRICULA, NOMBRE, APELLIDO) VALUES ('1234', 'Julian', 'Delgado'), ('4567', 'Serrana', 'Marset');