DROP TABLE IF EXISTS NOMBRE_TABLA;
CREATE TABLE ODONTOLOGOS (ID INT MATRICULA PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO INT NOT NULL);


-- para test --
INSERT INTO  ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('1234', 'Julian', 'Delgado'), ('4567', 'Serrana', 'Marset');