DROP TABLE IF EXISTS NOMBRE_TABLA;
CREATE TABLE NOMBRE_TABLA (ID INT AUTO_INCREMENT PRIMARY KEY, ATRIBUTO VARCHAR(100) NOT NULL, ATRIBUTO INT NOT NULL, ATRIBUTO VARCHAR(100) NOT NULL, ATRIBUTO VARCHAR(100) NOT NULL);


-- para test --
INSERT INTO  NOMBRE_TABLA(ATRIBUTO, ATRIBUTO, ATRIBUTO, ATRIBUTO) VALUES ('Valores atributos', 742, 'Valores atributos', 'Valores atributos'), ('Valores atributos', 42, 'Valores atributos', 'Valores atributos');